[package]
name = "lofi-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
lofi-core = { workspace = true }
lofi-error = { workspace = true }
lofi-types = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
ratatui = { workspace = true, features = ["unstable-rendered-line-info"] }
crossterm = { workspace = true }
nix = { workspace = true }
unicode-width = { workspace = true }
unicode-segmentation = { workspace = true }
base64 = { workspace = true }
pulldown-cmark = { workspace = true }
dirs = { workspace = true }
serde_json = { workspace = true }
serde = { workspace = true }
lz4_flex = { workspace = true }
similar = { workspace = true }
clap = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }

[lints]
workspace = true