[package]
name = "lofi-ui"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
lofi-core = { workspace = true }
lofi-error = { workspace = true }
lofi-types = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
ratatui = { workspace = true, features = ["unstable-rendered-line-info"] }
crossterm = { workspace = true }

[lints]
workspace = true