[package]
name = "lofi"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
lofi-ui = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing-subscriber = { workspace = true }

[lints]
workspace = true